# Schema for the configuration files of the Hello custom Module module.
module_bmcoder.settings:
  type: config_object
  label: 'Hello custom Module settings'
  mapping:
    api_key:
      type: string
      label: 'API Key'
    response_format:
      type: string
      label: 'Response Format'
    notification_type:
      type: string
      label: 'Notification Type'
